### ISSUE TITLE
Pass Action File

### ISSUE THREAD

**Issue by michaelpietzsch** [UiP9AV6Y/dockerfiles#10]
How do i pass an action file in to the system?

**Comment by UiP9AV6Y** [comment]
which image are we talking about here?

**Comment by michaelpietzsch** [comment]
I was wondering if its is possible to pass an action file rather than setting multiple env statements on the curator-cron image

**Comment by UiP9AV6Y** [comment]
you can try it with the following environment variables:
```yaml
CURATOR_EXECUTABLE: /usr/local/bin/curator
CURATOR_CRON_CONFIG: /data/curator.yml
CURATOR_CRON_SCHEDULE_DAILY_ACTION_FILE: '0 0 * * *|/data/actions_daily.yml|2>&1'
CURATOR_CRON_SCHEDULE_WEEKLY_ACTION_FILE: '30 12 * * 1|/data/actions_weekly.yml|2>&1'
```

this assumes the [curator config](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html) at /data/curator.yml and your [action file](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/actionfile.html) at /data/actions_daily.yml and /data/actions_weekly.yml (adjust accordingly if you only have a single action file)

i have *not* tested this, so YMMV
