### ISSUE TITLE
PowerDNS-admin docker image error

### ISSUE THREAD

**Issue by jerheij** [UiP9AV6Y/dockerfiles#5]
I try to use the powerdns and powerdns-admin sqlite3 docker images but I get the following error when trying to run the powerdns containers:

> pdns-admin    | Traceback (most recent call last):                             
> pdns-admin    |   File "create_db.py", line 4, in <module>
> pdns-admin    |     from config import SQLALCHEMY_DATABASE_URI
> pdns-admin    | ImportError: No module named config     

My docker-compose.yml:
```
---
version: "3"
services:
  pdns-main:
    image: uip9av6y/powerdns:sqlite3
    container_name: pdns-main
    restart: always
    environment:
      DB_HOST: /data/pdns.db
    volumes:
      - ./pdns:/data
    networks:
      - infra
  pdns-admin:
    image: uip9av6y/powerdns-admin:sqlite3
    container_name: pdns-admin
    environment:
      UWSGI_PROTOCOL: uwsgi
      POWERDNS_ADMIN_DB_URI: 'sqlite:////data/pdns-admin.db'
      POWERDNS_ADMIN_CONF: /data/config.py
      POWERDNS_ADMIN_API_URL: http://nameserver:8081/
      POWERDNS_ADMIN_API_KEY: example
      POWERDNS_ADMIN_USERNAME: admin
      POWERDNS_ADMIN_PASSWORD: admin
    volumes:
      - ./pdns-admin:/data
    networks:
      - infra
networks:
  infra:
    external: true
```

After running the powerdns-admin container with the "docker run" command I found out there is no pip config module installed, is this related or is my configuration wrong?
